language: objective-c
osx_image: xcode9
env:
  - SCHEME="Valet iOS";SDK="iphonesimulator";DESTINATION="platform=iOS Simulator,OS=11.0,name=iPhone 7";ACTION="build test"
  - SCHEME="Valet tvOS";SDK="appletvsimulator11.0";DESTINATION="platform=tvOS Simulator,name=Apple TV";ACTION="build test"
  - SCHEME="Valet Mac";SDK="macosx10.13";DESTINATION="platform=OS X";ACTION="build test"
  - SCHEME="Valet watchOS";SDK="watchos4.0";DESTINATION="platform=watchOS Simulator,OS=4.0,name=Apple Watch - 42mm";ACTION="build"
install:
  - bundle install
  - brew outdated carthage || brew upgrade carthage
before_script:
  - bundle exec pod lib lint --verbose --fail-fast
  - carthage build --verbose --no-skip-current
script:
  - xcodebuild -project Valet.xcodeproj -scheme "$SCHEME" -sdk $SDK -destination "$DESTINATION" -configuration Debug -PBXBuildsContinueAfterErrors=0 $ACTION
